server:
  port: 9090
spring:
  thymeleaf:
    #开发阶段关闭thymeleaf的模板缓存
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    #连接数据库
  datasource:
    url: jdbc:mysql://120.79.43.25:3306/phone_store?useUnicode=true&characterEncoding=utf-8
    username: JavaWeb
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
